export enum NodeEventEnum {
  VIEW = 'view',
  RENAME = 'rename',
  ADD_NODE = 'add_node',
  ADD_CONTENT = 'add_content',
  GET_CONTENT = 'get_content',
  SELECT_NODE = 'selectNode',
  BACK = 'BACK',
  SELECT_OPERATION = 'selectOperation',
  EDIT = 'EDIT',
  ADD = 'ADD',
  OPEN = 'OPEN',
  DEL = 'DEL',
  SET_NODE_ID = 'SET_NODE_ID',
  GET_NODE_LIST = 'getNodeList',
}
